"""Generate suggested governance YAML from learning-run reports; evaluate policies for replay."""

from __future__ import annotations

import re
from datetime import datetime, timezone
from typing import Any

import yaml


def _eval_condition_string(
    condition: str,
    action_type: str,
    target: str,
    risk: str,
) -> bool:
    """Mirror backend ``policy._eval_condition`` for string conditions."""
    c = condition.strip()
    if c == "true":
        return True
    if "==" not in c:
        return False
    left, right = c.split("==", 1)
    left = left.strip()
    right = right.strip().strip("\"'")
    if left == "risk":
        return risk == right
    if left == "action_type":
        return action_type == right
    if left == "target":
        return target == right
    return False


def _match_rule_dict(match: dict[str, Any], action_type: str, target: str, risk: str) -> bool:
    """Extended matching used by suggested YAML (optional ``match`` blocks)."""
    if not match:
        return True
    if "action_type" in match and match["action_type"] != action_type:
        return False
    if "risk" in match and match["risk"] != risk:
        return False
    if "target_contains" in match:
        if str(match["target_contains"]) not in target:
            return False
    return True


def evaluate_policy(
    policy: dict[str, Any],
    action_type: str,
    target: str,
    risk: str,
) -> str:
    """
    First matching rule wins (same semantics as backend). Supports ``condition`` strings
    and optional ``match`` dicts for richer suggested policies.
    """
    rules = policy.get("rules") or []
    if not isinstance(rules, list):
        return "hold"
    for rule in rules:
        if not isinstance(rule, dict):
            continue
        verdict = str(rule.get("verdict") or "hold")
        if "match" in rule:
            m = rule.get("match")
            if isinstance(m, dict):
                if _match_rule_dict(m, action_type, target, risk):
                    return verdict
            elif m is None or m == {}:
                return verdict
            continue
        cond = str(rule.get("condition") or "false")
        if _eval_condition_string(cond, action_type, target, risk):
            return verdict
    return "hold"


def _slug(s: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "-", s.strip().lower()).strip("-")
    return s or "rule"


def suggest_policy(report: dict[str, Any]) -> str:
    """
    Analyze a governance report from a learning run and generate policy YAML.

    Uses ``condition`` strings compatible with the backend evaluator, plus optional
    ``match`` blocks where substring rules are needed (replay understands both).
    """
    agent_id = str(report.get("agent_id") or "agent")
    calls = report.get("calls") or []
    if not isinstance(calls, list):
        calls = []

    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    unique_targets = report.get("unique_targets") or []
    if not isinstance(unique_targets, list):
        unique_targets = []

    name = _slug(agent_id) + "-policy"
    total = int(report.get("total_calls") or len(calls))

    header = (
        f"# Auto-generated by: axiom suggest\n"
        f"# Based on learning run: {now}\n"
        f"# Agent: {agent_id}\n"
        f"# Observed: {total} calls across {len(unique_targets)} unique targets\n"
    )

    rules_out: list[dict[str, Any]] = []
    rule_keys: set[str] = set()

    def add_rule(r: dict[str, Any], key: str) -> None:
        if key in rule_keys:
            return
        rule_keys.add(key)
        rules_out.append(r)

    # Collect unique action types from observed calls
    seen_action_types: set[str] = set()
    read_targets: set[str] = set()
    for call in calls:
        if not isinstance(call, dict):
            continue
        at = str(call.get("action_type") or "")
        if at:
            seen_action_types.add(at)
        if at == "tool.http.read":
            tgt = str(call.get("target") or "")
            if tgt:
                read_targets.add(tgt)

    for at in sorted(x for x in seen_action_types if x.startswith("tool.llm.")):
        add_rule(
            {
                "name": f"allow-{_slug(at)}",
                "condition": f'action_type == "{at}"',
                "verdict": "allow",
            },
            f"llm:{at}",
        )

    if "tool.http.read" in seen_action_types:
        add_rule(
            {
                "name": "allow-http-read",
                "condition": 'action_type == "tool.http.read"',
                "verdict": "allow",
            },
            "allow:tool.http.read",
        )

    for tgt in sorted(read_targets):
        add_rule(
            {
                "name": f"allow-read-{_slug(tgt)[:48]}",
                "match": {
                    "action_type": "tool.http.read",
                    "target_contains": tgt[:200],
                },
                "verdict": "allow",
            },
            f"read_tgt:{tgt}",
        )

    add_rule(
        {
            "name": "hold-email",
            "match": {"action_type": "tool.email.send"},
            "verdict": "hold",
            "reason": "Messaging requires human approval",
        },
        "hold:tool.email.send",
    )
    add_rule(
        {
            "name": "hold-chat",
            "match": {"action_type": "tool.chat.send"},
            "verdict": "hold",
            "reason": "Messaging requires human approval",
        },
        "hold:tool.chat.send",
    )
    add_rule(
        {
            "name": "hold-webhook",
            "match": {"action_type": "tool.webhook"},
            "verdict": "hold",
            "reason": "Webhooks require human approval",
        },
        "hold:tool.webhook",
    )
    add_rule(
        {
            "name": "hold-unknown-writes",
            "match": {"action_type": "tool.http.write"},
            "verdict": "hold",
            "reason": "Write to unrecognized API requires approval",
        },
        "hold:tool.http.write",
    )
    add_rule(
        {
            "name": "deny-default",
            "match": {},
            "verdict": "deny",
            "reason": "Default deny — add explicit allow rules for new targets",
        },
        "deny:default",
    )

    doc: dict[str, Any] = {
        "name": name,
        "version": 1,
        "description": f"Auto-generated policy for {agent_id} based on observed behavior",
        "rules": rules_out,
    }

    body = yaml.safe_dump(
        doc,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
    )
    return header + "\n" + body
